style:
  text-align: left

article:
  license: 

footer:
  content: |
    Friends [Mairen](https://mairen.moitr.com:5245)
    Powered by [Hexo](https://hexo.io) & [{theme.name} {theme.version}]({theme.tree}) & [Cloudflare Pages](https://pages.cloudflare.com)